### ISSUE TITLE
Реализация дополнительного API метода

### ISSUE THREAD

**Issue by ElectroMyStyle** [sima-land/api-v5-php-client#11]
Приветствую, возможно ли попросить вас реализовать дополнительный метод получения информации о товаре по артикулу? Просто как-то странно, что на страницах товаров везде указан артикул и Id товара скрыто от глаз грубо говоря, а в API получить информацию о товаре можно только по его Id - https://www.sima-land.ru/api/v5/help/#/%D0%A2%D0%BE%D0%B2%D0%B0%D1%80%D1%8B ?

**Comment by pahanini** [comment]
Добрый день, постараемся реализовать

**Comment by ElectroMyStyle** [comment]
> Добрый день, постараемся реализовать

Добрый день, было бы здорово, спасибо

**Comment by pahanini** [comment]
Добавили получение по артикулу. По второе пожелание вынесли в отдельный issue https://github.com/sima-land/api-v5-php-client/issues/14

**Comment by ElectroMyStyle** [comment]
> Добавили получение по артикулу. По второе пожелание вынесли в отдельный issue #14

Спасибо. Было бы супер, если реализуете второе пожелание

**Comment by Lysenkov8** [comment]
> > Добавили получение по артикулу. По второе пожелание вынесли в отдельный issue #14
> 
> Спасибо. Было бы супер, если реализуете второе пожелание.

Добрый день. Поступила информация от разработчиков что добавили нужное поле.
