### ISSUE TITLE
Конфликт версий зависимостей

### ISSUE THREAD

**Issue by PantiL** [sima-land/api-v5-php-client#12]
Здравствуйте. Библиотека API зависит от пакета monolog/monolog ~1 . Это очень старая версия. И не получается установить библиотеку в проект на Symfony. У меня уже используется monolog версии 2.6
Может есть возможность поднять версию пакета в зависимостях?

**Comment by Lysenkov8** [comment]
Добрый день

Просьбу передал разработчикам, в ближайшее время дадут обратную связь и возможно возьмут в работу

**Comment by Lysenkov8** [comment]
Добрый день, были обновлены версии
php 5.4 -> 7.2
monolog 1 -> 2.7.0
phpunit 4 -> 8.0.0
