### ISSUE TITLE
Добавить в выводе API категорию оптовой цены

### ISSUE THREAD

**Issue by pahanini** [sima-land/api-v5-php-client#14]
Добавить в выводе API категорию оптовой цены. Например, здесь - https://www.sima-land.ru/4588836/ есть оптовая цена и категория - Опт «Детские товары», а здесь - https://www.sima-land.ru/5407196/ просто Опт, без категории. В API возвращается только цена, а категории нет.

**Comment by Lysenkov8** [comment]
Разработчикам поставлена задача на добавление этой категории

**Comment by Lysenkov8** [comment]
Поступила информация от разработчиков что добавили нужное поле.
