### ISSUE TITLE
Как получить по запросу API картунку товара

### ISSUE THREAD

**Issue by repair-cat** [sima-land/api-v5-php-client#15]
В версии 5 все ссылки на картинки не соответсвуют примеру из описания API  и не работают по тому же принципу. Невозможно добавить какой-либо индекс и указать размер в запросе. всегда выдает ошибку. Так же пробовал просто сделать запрос по ссылке, которая указана в поле картинки товара. Результат одинаковый. Invalid argument.
Как же правильно составить запрос для получения картинки товара?

**Comment by Lysenkov8** [comment]
Добрый день

Не могли бы Вы предоставить примеры ваших запросов и ссылок в текстовом виде, что бы мы могли более подробно ознакомиться и разобраться?

**Comment by repair-cat** [comment]
Вот запрос на карточку товара - 
https://www.sima-land.ru/api/v5/item/600

вот что я получаю в ответ

{
    "id": 600,
    "sid": 604,
    "name": "лошадк. бр.фосф. мал.",
    "description": "",
    "slug": "loshadk-br-fosf-mal",
    "balance": "0",
    "price": 2.11,
    "box_depth": 0,
    "box_height": 0,
    "box_width": 0,
    "depth": 0,
    "height": 0,
    "width": 0,
    "weight": 0,
    "is_price_fixed": false,
    "is_adult": false,
    "is_markdown": false,
    "trademark_id": 0,
    "country_id": 156,
    "unit_id": 91,
    "nested_unit_id": 0,
    "base_photo_url": "https://cdn2.static1-sima-land.com/items/600/",
    "minimum_order_quantity": 0,
    "min_qty": 0,
    "qty_multiplier": 1,
    "is_paid_delivery": false,
    "supply_period": 0,
    "is_remote_store": false,
    "parent_item_id": 600,
    "barcodes": [
        "2900006040018",
        "2900604000001"
    ],
    "is_exclusive": false,
    "category_id": 0,
    "settlements_balance": [],
    "wholesale_price": 0,
    "price_max": 0,
    "is_protected": false
}

в карточке есть поле base_photo_url. Его значение я использую для запроса к фото.
Согласно документации составляю запрос - https://cdn2.static1-sima-land.com/items/600/0/140.jpg

ответ сервера 
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>InvalidArgument</Code>
    <Message>Invalid Argument</Message>
    <RequestId>305cbe5d-5a06-1fc1-906e-b4055d2f0e4c</RequestId>
    <HostId>d6bde86945e74f41a78967f80820655e</HostId>
</Error>

При использовании просто данной ссылки без индекса и размера такой же ответ сервера

**Comment by Lysenkov8** [comment]
Для данного товара нет фотографий. За наличие фотографий у товара отвечает поле agg_photos. Как видно, в примере данное поле отсутствует.
![image](https://user-images.githubusercontent.com/104409642/178411763-e9adfe9d-e597-461e-a306-87b357f6d9ee.png)

**Comment by repair-cat** [comment]
спасибо
