### ISSUE TITLE
Проблема с получением токена

### ISSUE THREAD

**Issue by kostya-php** [sima-land/api-v5-php-client#17]
При аутентификации возвращается 200 код, это условие не выполняется и скрипт завершает работу.

https://github.com/sima-land/api-v5-php-client/blob/0278eefed76694c2a2949e9c3fd8066130817da1/src/Rest/Client.php#L227

**Comment by Lysenkov8** [comment]
Добрый день,

Проблему передал разработчикам, в ближайшее время разберемся и вернемся к вам с ответом.

**Comment by Lysenkov8** [comment]
Добрый день
было выложено обновление, должно исправить ошибку
