### ISSUE TITLE
Установка через composer

### ISSUE THREAD

**Issue by Batyabest** [sima-land/api-v5-php-client#2]
Добрый день. При попытке установки через composer такой командой
`composer require "sima-land/api-v5-php-client:~1"`
выдает ошибку:

> Problem 1
>     - The requested package sima-land/api-v5-php-client could not be found in any versio
> n, there may be a typo in the package name.
>

**Comment by EvgenyGavrilov** [comment]
Здравствуйте.
Попробуйте заново выполнить команду `composer require sima-land/api-v5-php-client:~1`

**Comment by Batyabest** [comment]
Да, все отлично. Спасибо.
