### ISSUE TITLE
Получить только товары в наличии

### ISSUE THREAD

**Issue by Batyabest** [sima-land/api-v5-php-client#3]
Добрый день. Подскажите, можно ли получить только товары, что в наличии?
Пытаюсь так:
`$itemList = new \SimaLand\API\Entities\ItemList(
    $client,
    [
        'logger' => $logger,
        'getParams' => [
            'with_adult' => 1,
            'balance':'Достаточно'
        ],
    ]
);`
И так:
`$itemList = new \SimaLand\API\Entities\ItemList(
    $client,
    [
        'logger' => $logger,
        'getParams' => [
            'with_adult' => 1,
            'balance':1
        ],
    ]
);`
И так:
`$itemList = new \SimaLand\API\Entities\ItemList(
    $client,
    [
        'logger' => $logger,
        // Краткая информации по товару.
        'getParams' => [
            //"view"=>"brief"
            'with_adult' => 1,
            'balance':'1'
        ],
    ]
);`

не работает))

**Comment by makcumka** [comment]
> Как выяснилось, так он все-таки собирает те товары, у которых balance : 0. Значит, мой вопрос еще актуален для меня.

С таким параметром работает у меня:
`'has_balance'=>1`
