### ISSUE TITLE
Пользовательский класс Object не поддерживается новыми версиями PHP

### ISSUE THREAD

**Issue by dimqakolyada** [sima-land/api-v5-php-client#5]
При запуске библиотеки на новых версих PHP возникает ошибка:
> "Fatal error: Cannot use SimaLand\API\Object as Object because 'Object' is a special class name in /var/www/html/spchita/public/vendor/sima-land/api-v5-php-client/src/Rest/Client.php on line 8"

**Comment by EvgenyGavrilov** [comment]
Исправлено в версии 1.1.0
