### ISSUE TITLE
Товары определенного каталога

### ISSUE THREAD

**Issue by Qwoller** [sima-land/api-v5-php-client#7]
Здравствуйте,не могу понять,а как получить товары определенного каталога через ваше апи?

**Comment by EvgenyGavrilov** [comment]
Здравствуйте. В api v5 не предусмотрена фильтрация данных. Данное api предназначена для скачивания всего каталога, вы уже на своей стороне смотрите какие данные вам нужны.

**Comment by Qwoller** [comment]
А приблизительно сколько будет весить каталог всех товаров?
