### ISSUE TITLE
не работает parser_example.php

### ISSUE THREAD

**Issue by juridatsun** [sima-land/api-v5-php-client#8]
После установки через composer, указания логина и пароля, пытаюсь запустить parser_example.php 
Категории забирает, и на этом все. в логах следующее
![image](https://user-images.githubusercontent.com/23497895/122408484-1a163980-cf8b-11eb-98ad-58ee7c8ce871.png)

**Comment by pelmennoteam** [comment]
Очень похоже на то, что слишком часто выполняются запросы к серверу. Рекомендую реализовать небольшую паузу между запросами.
