### ISSUE TITLE
Не работает `parser_example.php`

### ISSUE THREAD

**Issue by error1001es** [sima-land/api-v5-php-client#9]
При запуске parser_example.php из корня репозитория выдает ошибку
`PHP Fatal error:  Uncaught Exception: Bad Request in C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\Rest\Client.php:229
Stack trace:
#0 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\Rest\Client.php(285): SimaLand\API\Rest\Client->auth()
#1 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\Rest\Client.php(208): SimaLand\API\Rest\Client->getToken()
#2 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\Rest\Client.php(131): SimaLand\API\Rest\Client->getOptions(Object(SimaLand\API\Rest\Request))
#3 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\AbstractList.php(169): SimaLand\API\Rest\Client->batchQuery(Array)
#4 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\AbstractList.php(299): SimaLand\API\AbstractList->get()
#5 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\AbstractList.php(343): SimaLand\API\AbstractList->getResponses()
#6 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\AbstractList.php(231): SimaLand\API\AbstractList->getData()
#7 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\AbstractList.php(260): SimaLand\API\AbstractList->next()
#8 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\Parser\Parser.php(112): SimaLand\API\AbstractList->rewind()
#9 C:\Users\pc\Desktop\sima-ozon\index.php(197): SimaLand\API\Parser\Parser->run()
#10 {main}
  thrown in C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\Rest\Client.php on line 229

Fatal error: Uncaught Exception: Bad Request in C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\Rest\Client.php:229
Stack trace:
#0 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\Rest\Client.php(285): SimaLand\API\Rest\Client->auth()
#1 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\Rest\Client.php(208): SimaLand\API\Rest\Client->getToken()
#2 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\Rest\Client.php(131): SimaLand\API\Rest\Client->getOptions(Object(SimaLand\API\Rest\Request))
#3 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\AbstractList.php(169): SimaLand\API\Rest\Client->batchQuery(Array)
#4 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\AbstractList.php(299): SimaLand\API\AbstractList->get()
#5 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\AbstractList.php(343): SimaLand\API\AbstractList->getResponses()
#6 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\AbstractList.php(231): SimaLand\API\AbstractList->getData()
#7 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\AbstractList.php(260): SimaLand\API\AbstractList->next()
#8 C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\Parser\Parser.php(112): SimaLand\API\AbstractList->rewind()
#9 C:\Users\pc\Desktop\sima-ozon\index.php(197): SimaLand\API\Parser\Parser->run()
#10 {main}
  thrown in C:\Users\pc\Desktop\sima-ozon\vendor\sima-land\api-v5-php-client\src\Rest\Client.php on line 229`

**Comment by Lysenkov8** [comment]
Добрый день

Сейчас трудно будет понять в чем были причины такой ошибки, но парсер выдал статус ошибки Bad Request. Стоит данное исключение обрабатывать.
